/**
 * ESLint configuration.
 *
 * CLAUDE.md 7.1 lists what must not appear in this codebase: `any`, unchecked
 * type assertions, untyped JSON, floating promises, swallowed errors. Those are
 * lint rules, and until now nothing enforced them -- `pnpm lint` ran
 * `turbo run lint` against packages that defined no lint script, so it passed
 * by doing nothing.
 *
 * Type-aware rules are enabled deliberately. `no-floating-promises` and
 * `no-misused-promises` cannot work without type information, and they are two
 * of the specific prohibitions in 7.1, so the slower lint is the price of the
 * rule actually existing.
 */
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/migrations/**',
      // Generated by Next on every build; not ours to lint.
      '**/next-env.d.ts',
      'e2e/test-results/**',
      'e2e/playwright-report/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        // A single lint-only project rather than projectService. The
        // per-package tsconfigs include only `src`, so test files belonged to
        // no project and type-aware rules could not see them at all.
        project: ['./tsconfig.eslint.json'],
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node },
    },

    rules: {
      // --- Section 7.1, the explicit prohibitions ---
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',

      // "Swallowed errors". An empty catch block hides a failure entirely;
      // a catch that deliberately ignores must say so in a comment.
      'no-empty': ['error', { allowEmptyCatch: false }],

      // "Unchecked type assertions". Assertions are permitted where a local
      // invariant proves them, so this warns rather than errors: the goal is
      // to make each one visible, not to ban a construct the codebase needs
      // at parse boundaries.
      '@typescript-eslint/no-unnecessary-type-assertion': 'error',

      // "Untyped JSON" surfaces as unsafe member access on `any`. These are
      // warnings because parsed JSON legitimately arrives as `unknown` and is
      // narrowed; the warning marks where narrowing has not happened yet.
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-unsafe-return': 'warn',

      // Non-null assertions are permitted "unless proved by a local
      // invariant", so they warn and must be justified in review.
      '@typescript-eslint/no-non-null-assertion': 'warn',

      // Unused variables are a defect, not a style preference, but an
      // underscore prefix is the documented way to mark a deliberate one.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],

      '@typescript-eslint/require-await': 'warn',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-base-to-string': 'warn',
      '@typescript-eslint/restrict-template-expressions': 'off',
    },
  },

  // Tests assert on deliberately wrong shapes, so the unsafe-* family would
  // fire constantly on fixtures that are wrong on purpose.
  {
    files: ['**/test/**/*.ts', '**/*.test.ts', 'e2e/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // Browser code.
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    languageOptions: { globals: { ...globals.browser } },
  },

  // Plain scripts are not part of a tsconfig project, so no rule needing type
  // information can run on them. `disableTypeChecked` clears the preset's
  // type-aware rules but not ones enabled explicitly above, so those are
  // turned off here by name.
  {
    files: ['**/scripts/**/*.mjs', '*.mjs', '**/*.config.mjs'],
    ...tseslint.configs.disableTypeChecked,
    rules: {
      ...tseslint.configs.disableTypeChecked.rules,
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/await-thenable': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/no-base-to-string': 'off',
    },
  },
);
